# SPDX-FileCopyrightText: 2022 Red Hat, Inc.
# SPDX-License-Identifier: GPL-2.0-or-later

# Build stage

FROM alpine AS build
RUN apk add --no-cache --update build-base linux-headers python3 python3-dev py3-pip
WORKDIR /build
COPY ovirt-imageio.tar.gz .
RUN python3 -m venv /venv
RUN /venv/bin/pip install ovirt-imageio.tar.gz

# Final stage

FROM alpine
RUN apk add python3 qemu-img
RUN mkdir /etc/ovirt-imageio
COPY --from=build /venv /venv
COPY conf.d /etc/ovirt-imageio/conf.d
COPY app /app
EXPOSE 80/tcp
ENTRYPOINT [ "/app/entrypoint.py" ]
