#!/usr/bin/python
# vdsm-imaged - vdsm image daemon
# Copyright (C) 2015 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
"""
Test script for copying data from stdin to an image.

Examples:

    # Timing 1GiB copy to file
    time test/recvfile /var/tmp/image 1024 < /dev/zero
"""

import os
import sys
import argparse

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from imaged import directio
from imaged import util
from test import tool

parser = argparse.ArgumentParser(description='Receive image data from stdin')
parser.add_argument("-o", "--offset", dest="offset", type=int,
                    help="offset in image (in bytes)")
parser.add_argument("-b", "--buffer-size", dest="buffersize", type=int,
                    help="copy buffer size (in bytes)")
parser.add_argument("path", help="path to existing image")
parser.add_argument("size", type=int, help="amount of data to copy (in MiB)")
parser.set_defaults(offset=0, buffersize=directio.BUFFERSIZE)
args = parser.parse_args()

op = directio.Receive(args.path, sys.stdin, args.size * tool.MB,
                      offset=args.offset, buffersize=args.buffersize)
t = util.start_thread(op.run)
tool.progress(op)
t.join()
