#!/usr/bin/python
# vdsm-imaged - vdsm image daemon
# Copyright (C) 2015 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
"""
Test script for copying data from stdin to an image.

Usage:
    recvfile path megabytes

Note: path can be a file or a block device with enough room to write the
written data.

Examples:

    # Timing 1GiB copy to file
    time test/recvfile /var/tmp/image 1024 < /dev/zero
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from imaged import directio
from imaged import util
from test import tool

path = sys.argv[1]
size = int(sys.argv[2]) * tool.MB

op = directio.Receive(path, sys.stdin, size)
t = util.start_thread(op.run)
tool.progress(op)
t.join()
