.PHONY: rpm
rpm:
	python setup.py bdist_rpm --requires ovirt-imageio-common


.PHONY: srpm
srpm:
	python setup.py bdist_rpm --requires ovirt-imageio-common --source


.PHONY: dist
dist:
	python setup.py sdist
