#!/usr/bin/python3

# SPDX-FileCopyrightText: Red Hat, Inc.
# SPDX-License-Identifier: GPL-2.0-or-later

"""
Show how to compute disk image checksum.
"""
import sys
from ovirt_imageio import client

path = sys.argv[1]
res = client.checksum(path, algorithm="sha256")
print(f"{res['checksum']}  {path}")
