#!/usr/bin/python
# ovirt-imageio
# Copyright (C) 2018 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

"""
nbd client example

Show how to use nbd module to upload and download images to/from nbd server.

Usage
-----

Start qemu-nbd with a destination image in any format supported by
qemu-img.  To access raw images, you can also use nbdkit or nbd-server.

    $ qemu-nbd \
        --socket /tmp/nbd.sock \
        --format qcow2 \
        --export-name=export \
        --persistent \
        --cache=none \
        --aio=native \
        --discard=unmap \
        --detect-zeroes=unmap \
        image.qcow2

Upload raw file to qcow2 image via qemu-nbd:

    $ ./nbd-client -e export upload file.raw nbd:unix:/tmp/nbb.sock

Download qcow2 image to raw file via qemu-nbd:

    $ ./nbd-client -e export download nbd:unix:/tmp/nbb.sock file.raw
"""

import argparse
import io
import json
import os
import subprocess
import sys

from six.moves.urllib.parse import urlparse

from ovirt_imageio_common import nbd
from ovirt_imageio_common import ui


def upload(args):
    size = os.path.getsize(args.filename)
    with io.open(args.filename, "rb") as src, \
            nbd.open(urlparse(args.nbd_url)) as dst, \
            ui.ProgressBar(size) as pb:
        if dst.export_size < size:
            raise Exception("Destination size {} is smaller than source file "
                            "size {}".format(dst.export_size, todo))
        for zero, start, length in _map(args.filename):
            if zero:
                _zero_range(dst, start, length, pb)
            else:
                _copy_range(dst, src, start, length, pb, args.block_size)
        dst.flush()


def download(args):
    with nbd.open(urlparse(args.nbd_url)) as src, \
            io.open(args.filename, "wb") as dst:
        with ui.ProgressBar(src.export_size) as pb:
            max_step = min(src.maximum_block_size, args.block_size)
            offset = 0
            buf = bytearray(max_step)

            while offset < src.export_size:
                step = min(src.export_size - offset, max_step)
                view = memoryview(buf)[:step]
                src.readinto(offset, view)
                dst.write(view)
                offset += step
                pb.update(step)

            os.fsync(dst.fileno())


def _map(path):
    out = subprocess.check_output([
        "qemu-img",
        "map",
        "--format", "raw",
        "--output", "json",
        path
    ])
    chunks = json.loads(out.decode("utf-8"))
    for c in chunks:
        yield c["zero"], c["start"], c["length"]


def _zero_range(dst, start, length, pb):
    while length:
        step = min(dst.maximum_block_size, length)
        dst.zero(start, step)
        start += step
        length -= step
        pb.update(step)


def _copy_range(dst, src, start, length, pb, block_size):
    max_step = min(dst.maximum_block_size, block_size)
    src.seek(start)
    while length:
        chunk = src.read(min(length, max_step))
        if not chunk:
            raise Exception("Unexpected end of file, expecting {} bytes"
                            .format(length))
        dst.write(start, chunk)
        n = len(chunk)
        start += n
        length -= n
        pb.update(n)


def kib(s):
    return int(s) * 1024


parser = argparse.ArgumentParser(description="nbd example")
parser.add_argument(
    "-b", "--block-size",
    # 4M is significantly faster than 8M on download, and about the same on
    # upload.
    default=4 * 1024**2,
    type=kib,
    help="block size in KiB")

commands = parser.add_subparsers(title="commands")

upload_parser = commands.add_parser(
    "upload",
    help="upload image data to nbd server")
upload_parser.set_defaults(command=upload)
upload_parser.add_argument(
    "filename",
    help="filename to copy")
upload_parser.add_argument(
    "nbd_url",
    help="NBD URL (nbd:unix:/sock or nbd:localhost:10809)")

download_parser = commands.add_parser(
    "download",
    help="download image data from nbd server")
download_parser.set_defaults(command=download)
download_parser.add_argument(
    "nbd_url",
    help="NBD URL (nbd:unix:/sock or nbd:localhost:10809)")
download_parser.add_argument(
    "filename",
    help="filename to write")

args = parser.parse_args()
args.command(args)
