#!/bin/bash

openssl req \
    -x509 \
    -nodes \
    -days 3650 \
    -subj "/CN=127.0.0.1" \
    -addext "subjectAltName=IP:127.0.0.1" \
    -newkey rsa:2048 \
    -keyout pki/keys/vdsmkey.pem \
    -out pki/certs/vdsmcert.pem
