# SPDX-FileCopyrightText: Red Hat, Inc.
# SPDX-License-Identifier: GPL-2.0-or-later

name: Containers
on:
  # Be able to run the job manually when needed
  # (Actions -> Containers -> Run workflow)
  workflow_dispatch:
  # Build every week on Monday 00:00
  schedule:
    - cron:  '0 0 * * 1'
env:
  IMAGE_REGISTRY: quay.io/ovirt
  can_push: ${{ github.repository_owner == 'oVirt' }}
jobs:
  test-containers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ centos-9, centos-10, almalinux-9, almalinux-10, fedora-43, fedora-44 ]
    steps:
      - uses: actions/checkout@v7
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install podman
      - name: Build container images
        working-directory: containers
        run: make ${{ matrix.distro }}
      - name: Push to Quay.io
        if: ${{ env.can_push == 'true' }}
        env:
          REGISTRY: ${{ env.IMAGE_REGISTRY }}
          IMAGE_NAME: ovirt-imageio-test
          NAME: ${{ matrix.distro }}
          USERNAME: ${{ secrets.QUAY_USERNAME }}
          PASSWORD: ${{ secrets.QUAY_TOKEN }}
        run: |
          podman push "${IMAGE_NAME}:${NAME}" "${REGISTRY}/${IMAGE_NAME}:${NAME}" --tls-verify=true --creds="${USERNAME}:${PASSWORD}"
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install podman
      - name: Build container images
        run: make container
      - name: Push to Quay.io
        if: ${{ env.can_push == 'true' }}
        env:
          REGISTRY: ${{ env.IMAGE_REGISTRY }}
          IMAGE_NAME: ovirt-imageio
          USERNAME: ${{ secrets.QUAY_USERNAME }}
          PASSWORD: ${{ secrets.QUAY_TOKEN }}
        run: |
          podman push "${IMAGE_NAME}" "${REGISTRY}/${IMAGE_NAME}" --tls-verify=true --creds="${USERNAME}:${PASSWORD}"
